### ISSUE TITLE
Class 'Crabbly\FPDF\FPDF' not found

### ISSUE THREAD

**Issue by nikunjsilvercayde** [crabbly/fpdf-laravel#5]
Hello

I installed composer require crabbly/fpdf-laravel in my lumen server and It's giving error of "Class 'Crabbly\FPDF\FPDF' not found" in my controller when I am trying to create PDF.

In my local server it's working fine, but in live server creating it's creating a problem. 

Can you please tell me how can I solve this error?

**Comment by crabbly** [comment]
Please try updating to v1.0.3

**Comment by crabbly** [comment]
This was fixed a few versions ago. Closing this issue. Feel free to open a new one if any other issues.
